-- 10 Bussiness Problems & Solutions
1. How can we split the combined genres in the listed_in column so each genre appears in its own row for detailed genre analysis?
2. Analyze Netflix's international content catalog (excluding U.S.) to gain insights into its global market penetration in different regions?
3. Find the distribution of TV Shows and Movies across genres and seasons?
4. Categorize Movies and TV Shows as Short ,Medium,or Long based on their runtime and find the content distribution?
5. Find the top 5 countries with the highest number of movies in the Netflix?
6. List all the movies directed by Rajiv Chilaka?
7. Classify content as 'Bad' if the description contains 'kill' or 'violence,' otherwise label it as 'Good.' Count the number of items in each category?
8. Analyze the lag between a title’s original release year and the date it was added to Netflix?
